<?xml version="1.0" encoding="UTF-8"?>
<testrun name="TestPrimeFactorization" project="Lab5" tests="8" started="8" failures="1" errors="0" ignored="0">
  <testsuite name="TestPrimeFactorization" time="0.002">
    <testcase name="testOne" classname="TestPrimeFactorization" time="0.0"/>
    <testcase name="testTwo" classname="TestPrimeFactorization" time="0.0"/>
    <testcase name="testThree" classname="TestPrimeFactorization" time="0.0"/>
    <testcase name="testFour" classname="TestPrimeFactorization" time="0.0"/>
    <testcase name="testSix" classname="TestPrimeFactorization" time="0.0"/>
    <testcase name="testEight" classname="TestPrimeFactorization" time="0.0"/>
    <testcase name="testNine" classname="TestPrimeFactorization" time="0.0"/>
    <testcase name="testThreeHundredAndTwentyFiveThousandOneHundredAndFifteen" classname="TestPrimeFactorization" time="0.002">
      <failure>java.lang.AssertionError: expected:&lt;[5, 7, 7, 1327]&gt; but was:&lt;[325115]&gt;
	at org.junit.Assert.fail(Assert.java:91)
	at org.junit.Assert.failNotEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:126)
	at org.junit.Assert.assertEquals(Assert.java:145)
	at TestPrimeFactorization.testThreeHundredAndTwentyFiveThousandOneHundredAndFifteen(TestPrimeFactorization.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</failure>
    </testcase>
  </testsuite>
</testrun>
